#!/bin/bash

# async-parent: Asynchronous execution demo (parent)

echo "Parent: starting..."

echo "Parent: launching child script..."
./async_child &
pid=$!
echo "Parent: Child (PID = $pid) launched."

echo "Parent: continuing..."
sleep 2

echo "Parent: pausing to wait for child to finish..."
wait "$pid"

echo "Parent: Child is finished. Continuing..."
echo "Parent: parent is done. Exiting."

